// <auto-generated />
using System;
using Domain.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Domain.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Enitiies.Qtype", b =>
                {
                    b.Property<int>("QtypeID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired();

                    b.HasKey("QtypeID");

                    b.ToTable("Qtypes");
                });

            modelBuilder.Entity("Domain.Enitiies.Question", b =>
                {
                    b.Property<int>("QuestionID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Answer")
                        .IsRequired();

                    b.Property<string>("Body")
                        .IsRequired();

                    b.Property<int>("QtypeID");

                    b.Property<int?>("SongId");

                    b.HasKey("QuestionID");

                    b.HasIndex("QtypeID");

                    b.HasIndex("SongId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("Domain.Enitiies.Song", b =>
                {
                    b.Property<int>("SongId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Url")
                        .IsRequired();

                    b.HasKey("SongId");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("Domain.Enitiies.Question", b =>
                {
                    b.HasOne("Domain.Enitiies.Qtype", "qtype")
                        .WithMany("question")
                        .HasForeignKey("QtypeID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.Enitiies.Song", "song")
                        .WithMany("question")
                        .HasForeignKey("SongId");
                });
#pragma warning restore 612, 618
        }
    }
}
